### PR TITLE
Pass parsed json response for errors to be compatible with boto 2.3

### PR DESCRIPTION
**Pull request by rhettg**
The API for DynamoDBResponseError changed as a result of
https://github.com/boto/boto/issues/625

### CODE REVIEW

**Comment by TelegramSam** [comment]
I would love this to be merged.

**Comment by danielhfrank** [comment]
Sorry guys, thought I had myself set up for notifications on this repo but have missed these requests - gimme a little bit of time to refamiliarize and I should be able to help make some progress here

**Comment by rhettg** [comment]
This latest commit isn't strictly Boto related, but I've seen some failures from DynamoDB that don't have JSON responses.

**Comment by danielhfrank** [comment]
Hey @rhettg let me know if you are planning on adding any more changes to this pull req, otherwise I can merge and get versions straightened out. Thanks for contributing!

**Comment by rhettg** [comment]
It seems pretty solid for now.

However, whatever condition causes us to hit that no-json response issue happens pretty rarely, don't think we've seen it in a few days. 

I'd say go ahead and merge.

**Comment by danielhfrank** [comment]
:shipit:

**Pull request merged**
